# please put any sensitive information or computer specific settings in private.yml!

default:
  collection: bandhistory

  data_base: https://servername.unl.edu/media
  media_base: https://servername.unl.edu
  tei_html_xsl: scripts/overrides/tei_to_html.xsl
  api_version: "2.0"

development:
  es_path: https://servername.unl.edu/elastic
  es_index: cdrhapidev-v2
  site_url: https://servername.unl.edu/bandhistory_rails

production:
  # limit processed files by adding allowed ids on newlines in a file
  # allowed_files: config/allowed.txt
  es_path: https://cdrhapi.unl.edu/elastic
  es_index: cdrhapi-v2
  site_url: https://bandhistory.unl.edu

